name: xc7
channels:
  - symbiflow
dependencies:
  - symbiflow::symbiflow-yosys
  - symbiflow::symbiflow-yosys-plugins=1.0.0.7_0032_g104f4fc
  - symbiflow::symbiflow-vtr=8.0.0.rc2_3575_g253f75b6d
  - make
  - lxml
  - simplejson
  - intervaltree
  - git
  - pip
  # Packages installed from PyPI
  - pip:
    - -r file:requirements.txt
