os: linux
dist: bionic
language: c++
env:
  global:
       - DEBIAN_FRONTEND: noninteractive
addons:
  apt:
    packages:
        - wget
        - locales
        - python-pip

before_install:
        - sudo locale-gen "en_US.UTF-8"
        - export LANG="en_US.UTF-8"
        - pip install git+https://github.com/antmicro/tuttest

install:
        - tuttest README.md unnamed0 > ci-install.sh
        - bash ci-install.sh

script:
        - export INSTALL_DIR=/opt/symbiflow
        - # adding symbiflow toolchain binaries to PATH
        - export PATH=$INSTALL_DIR/install/bin:$PATH
        - source $INSTALL_DIR/conda/etc/profile.d/conda.sh
        - conda activate
        - git clone https://github.com/SymbiFlow/symbiflow-examples && cd symbiflow-examples
        - # counter example
        - pushd counter_test && make && popd
        - # picosoc example
        - pushd picosoc_demo && make && popd
        - # litex example
        - pushd linux_litex_demo && make && popd
