name: xc7
channels:
  - symbiflow
dependencies:
  - symbiflow::symbiflow-yosys=0.8_6021_gd8b2d1a2=20200708_083630
  - symbiflow::symbiflow-yosys-plugins=1.0.0.7_0060_g7454cd6=20200902_114536
  - symbiflow::symbiflow-vtr=8.0.0.rc2_4003_g8980e4621
  - symbiflow::prjxray-db=0.0_0232_g303a61d=20200902_114536
  - symbiflow::prjxray-tools
  - make
  - lxml
  - simplejson
  - intervaltree
  - git
  - pip
  - openocd
  # Packages installed from PyPI
  - pip:
    - -r file:requirements.txt
