name: eos-s3
channels:
  - antmicro/label/ql
dependencies:
  - antmicro/label/ql::yosys
  - antmicro/label/ql::yosys-plugins
  - antmicro/label/ql::vtr
  - make
  - lxml
  - simplejson
  - intervaltree
  - git
  - pip
  # Packages installed from PyPI
  - pip:
    - -r file:requirements.txt
