name: Autobump

concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:


  Matrices:
    runs-on: ubuntu-latest
    outputs:
      debian: ${{ steps.generate.outputs.debian }}
      ubuntu: ${{ steps.generate.outputs.ubuntu }}
      fedora: ${{ steps.generate.outputs.fedora }}
      centos: ${{ steps.generate.outputs.centos }}
    steps:
      - uses: actions/checkout@v3
      - id: generate
        run: ./.github/scripts/generate_job_matrices.py '${{ github.repository }}'


  Debian:
    needs: Matrices
    uses: ./.github/workflows/sphinx-tuttest.yml
    with:
      matrix: ${{ needs.Matrices.outputs.debian }}
      latest: true

  Ubuntu:
    needs: Matrices
    uses: ./.github/workflows/sphinx-tuttest.yml
    with:
      matrix: ${{ needs.Matrices.outputs.ubuntu }}
      latest: true

  Fedora:
    needs: Matrices
    uses: ./.github/workflows/sphinx-tuttest.yml
    with:
      matrix: ${{ needs.Matrices.outputs.fedora }}
      latest: true

  Centos:
    needs: Matrices
    uses: ./.github/workflows/sphinx-tuttest.yml
    with:
      matrix: ${{ needs.Matrices.outputs.centos }}
      latest: true


  Autobump:
    needs:
      - Debian
      - Ubuntu
      - Fedora
      - Centos
    runs-on: ubuntu-latest
    name: Autobump arch-defs packages
    #permissions:
    #  contents: write

    steps:

      - name: Trigger hardware-ci tests
        run: |
          echo TODO

      - name: Wait for hardware-ci tests to finish
        run: |
          echo TODO

      - name: Bump arch-defs packages
        run: |
          echo TODO
