name: doc-test

on: [push, pull_request]

jobs:
  test-sphinx-docs:
    runs-on: [self-hosted, Linux, X64]
    strategy:
      fail-fast: false
      matrix:
        include:
          - {fpga-fam: "eos-s3", os: "ubuntu", os-version: "xenial",   example: "counter", n: 1}
          - {fpga-fam: "eos-s3", os: "ubuntu", os-version: "xenial",   example: "counter", n: 2}
          - {fpga-fam: "eos-s3", os: "ubuntu", os-version: "xenial",   example: "counter", n: 3}
          - {fpga-fam: "eos-s3", os: "ubuntu", os-version: "xenial",   example: "counter", n: 4}
          - {fpga-fam: "eos-s3", os: "ubuntu", os-version: "xenial",   example: "counter", n: 5}
          - {fpga-fam: "eos-s3", os: "ubuntu", os-version: "xenial",   example: "counter", n: 6}
          - {fpga-fam: "eos-s3", os: "ubuntu", os-version: "xenial",   example: "counter", n: 7}
          - {fpga-fam: "eos-s3", os: "ubuntu", os-version: "xenial",   example: "counter", n: 8}
          - {fpga-fam: "eos-s3", os: "ubuntu", os-version: "xenial",   example: "counter", n": 9}
          - {fpga-fam: "eos-s3", os: "ubuntu", os-version: "xenial",   example: "counter", n: 10}
    env:
      LANG: "en_US.UTF-8"
      DEBIAN_FRONTEND: "noninteractive"
      BASH_CMD: "bash -ex -"

    container: ${{matrix.os}}:${{matrix.os-version}}

    steps:
      - name: Setup repository
        uses: actions/checkout@v2
      
      - name: Update Python (Xenial)
        if: ${{matrix.os == 'ubuntu' && matrix.os-version == 'xenial'}}
        run: |
          apt -qqy update && apt -qqy install software-properties-common
          add-apt-repository -y ppa:deadsnakes/ppa
          apt -qqy update && apt -qqy install python3.7
          update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.7 1
          
      - name: Set Up Python
        if: ${{matrix.os == 'ubuntu' || matrix.os == 'debian'}}
        run: |
          apt -qqy update && apt -qqy install git wget python3 python3-pip build-essential locales
          locale-gen $LANG

      - name: Set Up Python
        if: ${{matrix.os == 'centos' && matrix.os-version == '7'}}
        run: |
          yum -y install centos-release-scl 
          yum -y install rh-python36 
          yum -y install git 
          yum -y install wget
          yum -y groupinstall 'Development Tools'
          echo "/opt/rh/rh-python36/root/usr/bin" >> $GITHUB_PATH

      - name: Set Up Python
        if: ${{matrix.os == 'centos' && matrix.os-version == '8'}}
        run: |
          yum -y install python3 
          yum -y install git 
          yum -y install wget
          yum -y groupinstall 'Development Tools'

      - name: Install tuttest
        run: |
          pip3 install git+https://github.com/antmicro/tuttest#egg=tuttest

      - name: Install SymbiFlow toolchain
        run: bash .github/scripts/install-toolchain.sh ${{matrix.fpga-fam}} ${{matrix.os}} | ${BASH_CMD}

      - name: Build examples
        run: bash .github/scripts/build-examples.sh ${{matrix.fpga-fam}} ${{matrix.example}} | ${BASH_CMD}

      - uses: actions/upload-artifact@v2
        with:
          name: symbiflow-examples-bitstreams
          path: |
            **/*.bit
