name: doc-test

on: [push, pull_request]

jobs:
  test-sphinx-docs:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - {fpga-fam: "eos-s3", os: "ubuntu", os-version: "bionic", example: "counter"}
          - {fpga-fam: "eos-s3", os: "ubuntu", os-version: "eoan",   example: "counter"}
          - {fpga-fam: "eos-s3", os: "ubuntu", os-version: "focal",  example: "counter"}

          - {fpga-fam: "xc7",    os: "ubuntu", os-version: "bionic", example: "counter"}
          - {fpga-fam: "xc7",    os: "ubuntu", os-version: "eoan",   example: "counter"}
          - {fpga-fam: "xc7",    os: "ubuntu", os-version: "focal",  example: "counter"}

          - {fpga-fam: "xc7",    os: "ubuntu", os-version: "bionic", example: "picosoc"}
          - {fpga-fam: "xc7",    os: "ubuntu", os-version: "eoan",   example: "picosoc"}
          - {fpga-fam: "xc7",    os: "ubuntu", os-version: "focal",  example: "picosoc"}

          - {fpga-fam: "xc7",    os: "ubuntu", os-version: "bionic", example: "litex"}
          - {fpga-fam: "xc7",    os: "ubuntu", os-version: "eoan",   example: "litex"}
          - {fpga-fam: "xc7",    os: "ubuntu", os-version: "focal",  example: "litex"}
    env:
      LANG: "en_US.UTF-8"
      DOCKER_NAME: test

    steps:
      - name: Setup repository
        uses: actions/checkout@v2

      - name: Setup Docker
        run: |
            docker create --name $DOCKER_NAME -v $PWD:$PWD --workdir $PWD --tty ${{matrix.os}}:${{matrix.os-version}}
            docker start $DOCKER_NAME

      - name: Install tuttest
        run: docker exec -t $DOCKER_NAME scripts/ci/install-deps.sh ${{matrix.os}}

      - name: Setup Conda environment
        run: docker exec -t $DOCKER_NAME scripts/ci/install-toolchain.sh ${{matrix.fpga-fam}}
        
      - name: Build examples
        run: docker exec -t $DOCKER_NAME scripts/ci/build.sh ${{matrix.fpga-fam}} ${{matrix.example}}
