name: doc-test

on: [push, pull_request]

jobs:
  test-sphinx-docs:
    runs-on: [self-hosted, Linux, X64]
    strategy:
      fail-fast: false
      matrix:
        include:
          - {fpga-fam: "eos-s3", os: "ubuntu", os-version: "xenial",   example: "counter"}
          - {fpga-fam: "eos-s3", os: "ubuntu", os-version: "bionic",   example: "counter"}
          - {fpga-fam: "eos-s3", os: "ubuntu", os-version: "focal",    example: "counter"}
          - {fpga-fam: "eos-s3", os: "centos", os-version: "7",        example: "counter"}
          - {fpga-fam: "eos-s3", os: "centos", os-version: "8",        example: "counter"}
          - {fpga-fam: "eos-s3", os: "debian", os-version: "buster",   example: "counter"}
          - {fpga-fam: "eos-s3", os: "debian", os-version: "bullseye", example: "counter"}
          - {fpga-fam: "eos-s3", os: "debian", os-version: "sid",      example: "counter"}

          - {fpga-fam: "xc7",    os: "ubuntu", os-version: "xenial",   example: "counter"}
          - {fpga-fam: "xc7",    os: "ubuntu", os-version: "bionic",   example: "counter"}
          - {fpga-fam: "xc7",    os: "ubuntu", os-version: "focal",    example: "counter"}
          - {fpga-fam: "xc7",    os: "centos", os-version: "7",        example: "counter"}
          - {fpga-fam: "xc7",    os: "centos", os-version: "8",        example: "counter"}
          - {fpga-fam: "xc7",    os: "debian", os-version: "buster",   example: "counter"}
          - {fpga-fam: "xc7",    os: "debian", os-version: "bullseye", example: "counter"}
          - {fpga-fam: "xc7",    os: "debian", os-version: "sid",      example: "counter"}

          - {fpga-fam: "xc7",    os: "ubuntu", os-version: "xenial",   example: "picosoc"}
          - {fpga-fam: "xc7",    os: "ubuntu", os-version: "bionic",   example: "picosoc"}
          - {fpga-fam: "xc7",    os: "ubuntu", os-version: "focal",    example: "picosoc"}
          - {fpga-fam: "xc7",    os: "centos", os-version: "7",        example: "picosoc"}
          - {fpga-fam: "xc7",    os: "centos", os-version: "8",        example: "picosoc"}
          - {fpga-fam: "xc7",    os: "debian", os-version: "buster",   example: "picosoc"}
          - {fpga-fam: "xc7",    os: "debian", os-version: "bullseye", example: "picosoc"}
          - {fpga-fam: "xc7",    os: "debian", os-version: "sid",      example: "picosoc"}

          - {fpga-fam: "xc7",    os: "ubuntu", os-version: "xenial",   example: "litex_linux"}
          - {fpga-fam: "xc7",    os: "ubuntu", os-version: "bionic",   example: "litex_linux"}
          - {fpga-fam: "xc7",    os: "ubuntu", os-version: "focal",    example: "litex_linux"}
          - {fpga-fam: "xc7",    os: "centos", os-version: "7",        example: "litex_linux"}
          - {fpga-fam: "xc7",    os: "centos", os-version: "8",        example: "litex_linux"}
          - {fpga-fam: "xc7",    os: "debian", os-version: "buster",   example: "litex_linux"}
          - {fpga-fam: "xc7",    os: "debian", os-version: "bullseye", example: "litex_linux"}
          - {fpga-fam: "xc7",    os: "debian", os-version: "sid",      example: "litex_linux"}
    env:
      LANG: "en_US.UTF-8"
      DEBIAN_FRONTEND: "noninteractive"

    container: ${{matrix.os}}:${{matrix.os-version}}

    steps:
      - name: Setup repository
        uses: actions/checkout@v2
      
      - name: Update Python (Xenial)
        if: ${{matrix.os == 'ubuntu' && matrix.os-version == 'xenial'}}
        run: |
          apt -qqy update && apt -qqy install software-properties-common
          add-apt-repository -y ppa:deadsnakes/ppa
          apt -qqy update && apt -qqy install python3.7
          update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.7 1
          
      - name: Set Up Python
        if: ${{matrix.os == 'ubuntu' || matrix.os == 'debian'}}
        run: |
          apt -qqy update && apt -qqy install git wget python3 python3-pip build-essential locales
          locale-gen $LANG

      - name: Set Up Python
        if: ${{matrix.os == 'centos' && matrix.os-version == '7'}}
        run: |
          yum -y install centos-release-scl 
          yum -y install rh-python36 
          yum -y install git 
          yum -y install wget
          yum -y groupinstall 'Development Tools'
          echo "/opt/rh/rh-python36/root/usr/bin" >> $GITHUB_PATH

      - name: Set Up Python
        if: ${{matrix.os == 'centos' && matrix.os-version == '8'}}
        run: |
          yum -y install python3 
          yum -y install git 
          yum -y install wget
          yum -y groupinstall 'Development Tools'

      - name: Install tuttest
        run: |
          pip3 install git+https://github.com/antmicro/tuttest#egg=tuttest

      - name: Install SymbiFlow toolchain
        run: bash .github/scripts/install-toolchain.sh ${{matrix.fpga-fam}} ${{matrix.os}} | bash -

      - name: Build examples
        run: bash .github/scripts/build-examples.sh ${{matrix.fpga-fam}} ${{matrix.example}} | bash -

      - uses: actions/upload-artifact@v2
        with:
          name: symbiflow-examples-bitstreams
          path: |
            **/*.bit
